# Generated by Django 4.0.1 on 2022-01-26 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('imagen', models.ImageField(blank=True, default='producto/default.jpg', upload_to='producto/categoria/%Y/%m/%d/%I/%M/%S/%p')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=60)),
                ('creadoEn', models.DateTimeField(auto_now_add=True)),
                ('modificadoEn', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('direccion', models.TextField(null=True)),
                ('documento', models.CharField(blank=True, max_length=13, null=True)),
                ('telefono', models.CharField(max_length=9, null=True)),
                ('redSocial', models.CharField(default='0', max_length=15)),
                ('activado', models.BooleanField(default=False)),
                ('codigo', models.CharField(max_length=4, null=True)),
                ('actualizacion', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (('is_negocio', 'Es Negocio'), ('is_establecimiento', 'Es Establecimiento'), ('is_repartidor', 'Es Repartidor')),
            },
        ),
        migrations.CreateModel(
            name='Detalle_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('latitud', models.CharField(max_length=20)),
                ('longitud', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Log_cambio_estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendiente', models.DateTimeField(auto_now_add=True)),
                ('visto', models.DateField(null=True)),
                ('preparado', models.DateField(null=True)),
                ('enviado', models.DateField(null=True)),
                ('entregado', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_pedido', models.DateTimeField(auto_now_add=True)),
                ('codigo_transaccion', models.CharField(max_length=100, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('latitud', models.CharField(max_length=20)),
                ('longitud', models.CharField(max_length=20)),
                ('latitud_origen', models.CharField(max_length=20, null=True)),
                ('longitud_origen', models.CharField(max_length=20, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('evaluacion', models.IntegerField(choices=[(1, 'Muy malo'), (2, 'Malo'), (3, 'Medianamente bueno'), (4, 'Bueno'), (5, 'Excelente')], null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('visto', 'Visto'), ('preparado', 'Preparado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=9)),
                ('creadoEn', models.DateTimeField(auto_now_add=True)),
                ('modificadoEn', models.DateTimeField(auto_now=True)),
                ('total', models.CharField(max_length=20, null=True)),
                ('precioDelivery', models.CharField(max_length=20, null=True)),
                ('player_id', models.CharField(max_length=100, null=True)),
                ('tipoPago', models.CharField(max_length=20, null=True)),
                ('tipoDocpago', models.IntegerField(choices=[(1, 'Boleta'), (2, 'Factura')], default=1)),
                ('docPago', models.TextField(null=True)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, default='producto/default.jpg', upload_to='producto/%Y/%m/%d/%I/%M/%S/%p')),
                ('descripcion', models.CharField(max_length=100)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('comida', 'Comida'), ('noPerecible', 'No perecible')], max_length=12)),
                ('precio', models.IntegerField()),
                ('precio_compra', models.IntegerField(null=True)),
                ('creadoEn', models.DateTimeField(auto_now_add=True)),
                ('modificadoEn', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('puntuacion', models.IntegerField(default=0, null=True)),
                ('vista', models.CharField(default=0, max_length=100)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFin', models.DateTimeField()),
                ('activo', models.BooleanField(blank=True, default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visita', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tags',
            field=models.ManyToManyField(to='administracion.Tags'),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.IntegerField(blank=True, choices=[(1, 'Administrador'), (2, 'Negocio'), (3, 'Establecimiento'), (4, 'Repartidor'), (5, 'Cliente')], default=2, null=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_llamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administracion.pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(through='administracion.Detalle_pedido', to='administracion.Producto'),
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFin', models.DateTimeField()),
                ('precioOferta', models.IntegerField()),
                ('activo', models.BooleanField(blank=True, default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.producto')),
            ],
        ),
        migrations.AddField(
            model_name='detalle_pedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='administracion.pedido'),
        ),
        migrations.AddField(
            model_name='detalle_pedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.producto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Localidad', to='administracion.localidad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to=settings.AUTH_USER_MODEL),
        ),
    ]
