# Generated by Django 4.0.1 on 2022-02-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_producto_cantidad_operacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_pedido',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='tipo_pago',
            field=models.IntegerField(choices=[(1, 'Efectivo'), (2, 'Electrónico'), (3, 'Transferencia'), (4, 'Otro')], null=True),
        ),
    ]
